openapi: 3.1.0
info:
  title: Thinkscribe Auth API
  version: 1.0.0
  description: Endpoints for authentication (login, register, etc.)
tags:
  - name: Auth
    description: Authentication related endpoints

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        This JWT is issued and validated by Clerk. To authenticate, use the access token provided by Clerk in the Authorization header:
        Authorization: Bearer <clerk_jwt_token>
        The token must be a valid Clerk session or access token. See https://clerk.com/docs/authentication/tokens for details.
  responses:
    '4XX':
      description: Error response (client error)
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              statusCode:
                type: integer
                example: 401
              message:
                type: string
                example: Unauthorized Access!
              data:
                type: array
                items:
                  type: object
                  properties:
                    path:
                      type: string
                      example: /api/v1/users
                    message:
                      type: string
                      example: Unauthorized Access!
              meta:
                type: object
                nullable: true
                example: null

security:
  - bearerAuth: []

paths:
  /auth/login:
    post:
      summary: Login
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
        '401':
          description: Unauthorized
  /auth/refresh-token:
    post:
      summary: Refresh access token
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: New access token
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        '401':
          description: Unauthorized
