openapi: 3.0.0
info:
  title: Users API
  version: 1.0.0
  description: Endpoints for user management
paths:
  /users:
    get:
      summary: Get all users
      tags: [Users]
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './openapi.yml#/components/schemas/User'
    post:
      summary: Create a new user
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openapi.yml#/components/schemas/User'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/User'
  /users/{id}:
    get:
      summary: Get a user by ID
      tags: [Users]
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/User'
    put:
      summary: Update a user
      tags: [Users]
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openapi.yml#/components/schemas/User'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/User'
    delete:
      summary: Delete a user
      tags: [Users]
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: User deleted
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/User'
